### PR TITLE
la-x-liturgical: sync with https://github.com/gregorio-project/hyphen-la

### PR DESCRIPTION
**Pull request by eroux**

### CODE REVIEW

**Comment by reutenauer** [comment]
That’s merged, thanks for the pull request.  We’ll submit an update to CTAN in the next few weeks.

**Comment by eroux** [comment]
Thank you!

**Comment by reutenauer** [comment]
You’re welcome!  If you submit more pull requests in the future it’s best to edit the TeX file because that’s what we use as the master data and we have scripts to generate the plain text files from that; not the other way round.

**Comment by eroux** [comment]
Oh ok, I think it would be useful to add this in a `CONTRIBUTING.md` file (github has a nice feature that displays it in relevant places, like when users want to build pull requests)

**Pull request merged**
